### ISSUE TITLE
Can I use `@type bigquery_insert` with the gem being released now?

### ISSUE THREAD

**Issue by abetomo** [kaizenplatform/fluent-plugin-bigquery#159]
## Environments
```
$ /opt/td-agent/embedded/bin/fluent-gem list fluent-plugin-bigquery

*** LOCAL GEMS ***

fluent-plugin-bigquery (1.2.0)
```

## Configuration
```
<match *.**>
  @type bigquery_insert
   ...
````

## Actual Behavior
`td-agent` will not start up due to error

## Log (if you have)
```
[error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'bigquery_insert'. Run 'gem search -rd fluent-plugin' to find plugins"
```

**Comment by joker1007** [comment]
Sorry, that config style is for v2.0.0, But I am testing v2.0.0.beta and not release yet.
I will release after a while.
Please wait. :sweat:

**Comment by abetomo** [comment]
@joker1007 Thank you for your reply!
I am looking forward to the release.

**Comment by joker1007** [comment]
I already released v2.0.0.beta.

**Comment by lluunn** [comment]
Hi @joker1007 ,

I am still seeing this error:

```
2018-07-19 23:23:35 +0000 [error]: config error file="/fluentd/etc/custom/fluent.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'bigquery_insert'. Run 'gem search -rd fluent-plugin' to find plugins"
```

I can see the gem from `gem list`: `fluent-plugin-bigquery (1.2.0)`

Any idea what might be the issue?

**Comment by lluunn** [comment]
filed #163
